name: Snapshot AUI release to Maven

on: workflow_dispatch

jobs:
    aui-release:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [0.12.18]

        steps:
            - name: maven-settings-xml-action
              uses: s4u/maven-settings-action@v2.3.0
              with:
                servers: |
                  [{
                      "id": "liferay-public-snapshots",
                      "username": "${{ secrets.MAVEN_USERNAME }}",
                      "password": "${{ secrets.MAVEN_PASSWORD }}"
                  }]

            - uses: actions/checkout@v4
              with:
                repository: liferay/liferay-frontend-projects

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - run: npm i
              working-directory: third-party/projects/alloy-ui

            - run: npm i -g gulp@^3.8.5
              working-directory: third-party/projects/alloy-ui

            - run: gulp init
              working-directory: third-party/projects/alloy-ui

            - run: gulp build
              working-directory: third-party/projects/alloy-ui

            - run: gulp maven-publish-snapshot
              working-directory: third-party/projects/alloy-ui

            - name: Cache AUI Build
              uses: actions/cache@v3
              with:
                key: ${{github.run_id}}-build
                path: third-party/projects/alloy-ui/build
